# import #

In [322]:
import json
import re
import sys
import chardet
from datetime import datetime
import pandas as pd
import numpy as np
from google.cloud import bigquery
from google.oauth2 import service_account
from google.api_core.exceptions import GoogleAPICallError
import schema

## import configuration ##

In [323]:
environment = 'prod'
try:
    with open("env") as f:
        environment = f.read()
finally:
    pass
    
environment

'test'

In [324]:
if environment == 'test':
    config_file = "configuration-test.json"
else:
    config_file = "configuration.json"

with open(config_file) as f:
    config = json.load(f)

config_file

'configuration-test.json'

# import data file #

try to load data from template without headers

In [325]:
import_file = 'CA_CIR_03-08-2026_15h09.csv'
log_file = 'import.log'
partner = 'testpartner'
date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
partner_config_file = 'partner_config.json'

if re.match('import_turnover.py', sys.argv[0]):
    if len(sys.argv) >= 1:
        import_file = sys.argv[1]
    if len(sys.argv) >= 2:
        log_file = sys.argv[2]
    if len(sys.argv) >= 3:
        partner = sys.argv[3]
    if len(sys.argv) >= 4:
        date = sys.argv[4]
    if len(sys.argv) >= 5:
        partner_config_file = sys.argv[5]

import data from file

In [326]:
with open(log_file, "w") as logfile:
    logfile.write(f"opening file {import_file} for reading\r\n")

detect encoding

In [327]:
sample_size=100000
with open(import_file, "rb") as f:
    rawdata = f.read(sample_size)
encoding = chardet.detect(rawdata)['encoding']

if encoding == 'ascii':
    encoding = 'latin-1'

with open(log_file, "a") as logfile:
    logfile.write(f"using encoding {encoding}\r\n")

define import setting

In [328]:
column_names = ['code_of_integration', 'member_branch_id', 'plant_id', 'product_family_id', 'supplier_id', 'product_id', 
                'supplier_product_reference', 'product_description', 'unit_net_price', 'quantity', 'turnover', 'price_per', 'sales_unit',
                'delivery_date', 'invoice_date', 'year', 'month', 'quarter', 'semester', 'member_order_nb', 'customer_order_nb', 'deliver_note',
                'invoice_nb', 'customer_reference', 'member_internal_reference', 'buying_member_id', 'member_id']
kwargs = {}
kwargs['filepath_or_buffer'] = import_file
kwargs['header'] = None
kwargs['index_col'] = False
kwargs['encoding'] = encoding
kwargs['names'] = column_names
kwargs['delimiter'] = ';'
kwargs['skiprows'] = 0

In [329]:
set_values = {}
if partner_config_file != '':
    with open(partner_config_file) as f:
        partner_config = json.load(f)

        if 'delimiter' in partner_config:
            kwargs['delimiter'] = partner_config['delimiter']
            print(f"using delimiter '{kwargs['delimiter']}'")

        if 'column_names' in partner_config:
            kwargs['names'] = partner_config['column_names']
            print(f"using columns '{kwargs['names']}'")

        if 'skiprows' in partner_config:
            kwargs['skiprows'] = partner_config['skiprows']
            print(f"skip '{kwargs['skiprows']}' leading rows")

        if 'quotechar' in partner_config:
            kwargs['quotechar'] = partner_config['quotechar']
            print(f"using qoutechar '{kwargs['quotechar']}'")

        if 'thousands' in partner_config:
            kwargs['thousands'] = partner_config['thousands']
            print(f"using thousands '{kwargs['thousands']}'")

        if 'decimal' in partner_config:
            kwargs['decimal'] = partner_config['decimal']
            print(f"using decimal '{kwargs['decimal']}'")

        if 'lineterminator' in partner_config:
            kwargs['lineterminator'] = partner_config['lineterminator']
            print(f"using lineterminator '{kwargs['lineterminator']}'")

        if 'set_values' in partner_config:
            set_values = partner_config['set_values']
            for key, value in set_values.items():
                print(f"force '{key}' = '{value}'")

using columns '['code_of_integration', 'member_branch_id', 'plant_id', 'product_family_id', 'supplier_id', 'product_id', 'supplier_product_reference', 'product_description', 'unit_net_price', 'quantity', 'turnover', 'price_per', 'sales_unit', 'delivery_date', 'invoice_date', 'year', 'month', 'quarter', 'semester', 'member_order_nb', 'customer_order_nb', 'deliver_note', 'invoice_nb', 'customer_reference', 'member_internal_reference']'

In [330]:
inp_df = pd.read_csv(**kwargs)

In [331]:
inp_df.head(10)

,code_of_integration,member_branch_id,plant_id,product_family_id,supplier_id,product_id,supplier_product_reference,product_description,unit_net_price,quantity,...,year,month,quarter,semester,member_order_nb,customer_order_nb,deliver_note,invoice_nb,customer_reference,member_internal_reference
0,CIR - 07_juillet - 2026 - 000041_FCLI,CIRALB,000041_FCLI,01_Roulements,000037_FFOUR,19833-FAIR,SNL 218,PALIER FONTE,140.84,1.0,...,2026,07_juillet,T3,S2,455554,5502266101,190711,26-212766,,SKF SNL 218
1,CIR - 07_juillet - 2026 - 000041_FCLI,CIRALB,000041_FCLI,01_Roulements,000037_FFOUR,21397-FAIR,22211 EK/C3,RLT ROT.RLX.55X100X25 KC3,42.43,2.0,...,2026,07_juillet,T3,S2,472310,5502268702,207504,26-212770,2079554,SKF 22211KC3
2,CIR - 07_juillet - 2026 - 000041_FCLI,CIRALB,000041_FCLI,01_Roulements,000037_FFOUR,21878-FAIR,6205-2RSH,RLT RIG.BIL.25X52X15,2.82,2.0,...,2026,07_juillet,T3,S2,471993,5502267988,204835,26-212769,2075724,SKF 6205 2RS
3,CIR - 07_juillet - 2026 - 000041_FCLI,CIRALB,000041_FCLI,01_Roulements,000037_FFOUR,22004-FAIR,6309-2Z/C3,RLT RIG.BIL.45X100X25,13.37,2.0,...,2026,07_juillet,T3,S2,462564,5502267413,204833,26-212768,,SKF 6309 2ZC3
4,CIR - 07_juillet - 2026 - 000041_FCLI,CIRALB,000041_FCLI,01_Roulements,000041_FFOUR,487042-FAIR,H2307,MANCHON DE SERRAGE,10.37,1.0,...,2026,07_juillet,T3,S2,454310,5502265438,189734,26-212765,,TIMK H2307
5,CIR - 07_juillet - 2026 - 000041_FCLI,CIRALB,000041_FCLI,01_Roulements,000041_FFOUR,502389-FAIR,23218EJW33C3,"RLT A ROT. SUR RLX. 90X160X52,4",167.80,1.0,...,2026,07_juillet,T3,S2,455554,5502266101,190711,26-212766,,TIMK 23218EJW33C3
6,CIR - 07_juillet - 2026 - 000041_FCLI,CIRALB,000041_FCLI,01_Roulements,000041_FFOUR,758615-FAIR,UK207,RLT AUTO-ALIG.ALESA.CONIQ,13.22,1.0,...,2026,07_juillet,T3,S2,454310,5502265438,189734,26-212765,,TIMK UK207
7,CIR - 07_juillet - 2026 - 000041_FCLI,CIRALB,000041_FCLI,02_Transmission mecanique,000436_FFOUR,NaN,POLYFLEX12,COURROIE RONDE D12,12.01,16.0,...,2026,07_juillet,T3,S2,437955,5502258788,192120,26-212760,,MAFD POLYFLEX12
8,CIR - 07_juillet - 2026 - 000041_FCLI,CIRALB,000041_FCLI,03_Transmission electromecanique,000436_FFOUR,NaN,342171,COUVERCLE L100 GC,28.50,3.0,...,2026,07_juillet,T3,S2,332919,5502230992,201307,26-212759,,LEG1 342171
9,CIR - 07_juillet - 2026 - 000041_FCLI,CIRALB,000041_FCLI,03_Transmission electromecanique,000436_FFOUR,NaN,342152,COUVERCLE L200 GC,43.90,6.0,...,2026,07_juillet,T3,S2,332919,5502230992,201307,26-212759,,LEG1 342152

In [332]:
inp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7230 entries, 0 to 7229
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   code_of_integration         7230 non-null   object
 1   member_branch_id            7230 non-null   object
 2   plant_id                    7230 non-null   object
 3   product_family_id           7230 non-null   object
 4   supplier_id                 7230 non-null   object
 5   product_id                  4594 non-null   object
 6   supplier_product_reference  7230 non-null   object
 7   product_description         7230 non-null   object
 8   unit_net_price              7230 non-null   float64
 9   quantity                    7230 non-null   float64
 10  turnover                    7230 non-null   float64
 11  price_per                   7230 non-null   int64
 12  sales_unit                  7230 non-null   object
 13  delivery_date               7230 non-null   object
 14  invoice_date                7230 non-null   object
 15  year                        7230 non-null   int64
 16  month                       7230 non-null   object
 17  quarter                     7230 non-null   object
 18  semester                    7230 non-null   object
 19  member_order_nb             7230 non-null   int64
 20  customer_order_nb           7230 non-null   object
 21  deliver_note                7230 non-null   int64
 22  invoice_nb                  7230 non-null   object
 23  customer_reference          7230 non-null   object
 24  member_internal_reference   7230 non-null   object
dtypes: float64(3), int64(4), object(18)
memory usage: 1.4+ MB

In [333]:
with open(log_file, "a") as logfile:
    logfile.write(f"read {len(inp_df)} lines\r\n")

## clean data ##

In [334]:
missing_columns = [c for c in column_names if c not in set(kwargs['names'])]
missing_mandatory = []
missing_empty = []
created_columns = []

if set_values:
    for key, value in set_values.items():
        inp_df[key]=value

for col in missing_columns:
    if col in ['product_id', 'sales_unit', 'delivery_date', 'quarter', 'semester', 'member_order_nb', 'customer_order_nb', 'deliver_note',
                'invoice_nb', 'customer_reference', 'member_internal_reference', 'buying_member_id']:
        inp_df[col] = ''
        missing_empty.append("'" + col + "'")
    elif col in ['unit_net_price', 'price_per']:
        inp_df[col] = 0.0
        missing_empty.append("'" + col + "'")
    elif not col in ['year', 'month', 'code_of_integration']:
        missing_mandatory.append("'" + col + "'")
        
if 'year' in missing_columns:
    inp_df['year']=pd.to_datetime(inp_df['invoice_date']).dt.year
    created_columns.append("'year'")

if 'month' in missing_columns:
    inp_df['month']=pd.to_datetime(inp_df['invoice_date']).dt.month
    created_columns.append("'month'")

inp_df = inp_df.fillna('')
inp_df['member_branch_id']=inp_df['member_branch_id'].astype("string")
inp_df['plant_id']=inp_df['plant_id'].astype("string")
inp_df['product_family_id']=inp_df['product_family_id'].astype("string")
inp_df['supplier_product_reference']=inp_df['supplier_product_reference'].astype("string")
inp_df['product_description']=inp_df['product_description'].astype("string")
inp_df['supplier_product_reference']=inp_df['supplier_product_reference'].astype("string")
inp_df['member_order_nb']=inp_df['member_order_nb'].astype("string")
inp_df['customer_order_nb']=inp_df['customer_order_nb'].astype("string")
inp_df['deliver_note']=inp_df['deliver_note'].astype("string")
inp_df['invoice_nb']=inp_df['invoice_nb'].astype("string")
inp_df['customer_reference']=inp_df['customer_reference'].astype("string")
inp_df['member_internal_reference']=inp_df['member_internal_reference'].astype("string")
inp_df['member_id']=inp_df['member_id'].astype("string")

if 'code_of_integration' in missing_columns:
    inp_df['code_of_integration']=inp_df['member_id'] + '-' + inp_df['month'].astype(str).str.zfill(2) + '-' + inp_df['year'].astype(str) + '-' + inp_df['plant_id']
    created_columns.append("'code_of_integration'")
else:
    inp_df['code_of_integration']=inp_df['code_of_integration'].astype("string")

message = ''
if len(missing_empty) > 0:
    missing_empty_str = ", ".join(missing_empty)
    message += f"added empty fields {missing_empty_str}\r\n"
if len(missing_mandatory) > 0 :
    missing_mandatory_str = ", ".join(missing_mandatory)
    message += f"mandatory fields {missing_mandatory_str} missing\r\n"
if len(created_columns) > 0 :
    created_columns_str = ", ".join(created_columns)
    message += f"created fields {created_columns_str}\r\n"

if message:
    with open(log_file, "a") as logfile:
        logfile.write(message)

KeyError: 'member_id'

In [308]:
inp_df.head(10)

,code_of_integration,member_branch_id,plant_id,product_family_id,supplier_id,product_id,supplier_product_reference,product_description,unit_net_price,quantity,...,quarter,semester,member_order_nb,customer_order_nb,deliver_note,invoice_nb,customer_reference,member_internal_reference,member_id,buying_member_id
0,CIR - 07_juillet - 2026 - 000041_FCLI,CIRALB,000041_FCLI,01_Roulements,000037_FFOUR,19833-FAIR,SNL 218,PALIER FONTE,140.84,1.0,...,T3,S2,455554,5502266101,190711,26-212766,,SKF SNL 218,000099_FMEM,
1,CIR - 07_juillet - 2026 - 000041_FCLI,CIRALB,000041_FCLI,01_Roulements,000037_FFOUR,21397-FAIR,22211 EK/C3,RLT ROT.RLX.55X100X25 KC3,42.43,2.0,...,T3,S2,472310,5502268702,207504,26-212770,2079554,SKF 22211KC3,000099_FMEM,
2,CIR - 07_juillet - 2026 - 000041_FCLI,CIRALB,000041_FCLI,01_Roulements,000037_FFOUR,21878-FAIR,6205-2RSH,RLT RIG.BIL.25X52X15,2.82,2.0,...,T3,S2,471993,5502267988,204835,26-212769,2075724,SKF 6205 2RS,000099_FMEM,
3,CIR - 07_juillet - 2026 - 000041_FCLI,CIRALB,000041_FCLI,01_Roulements,000037_FFOUR,22004-FAIR,6309-2Z/C3,RLT RIG.BIL.45X100X25,13.37,2.0,...,T3,S2,462564,5502267413,204833,26-212768,,SKF 6309 2ZC3,000099_FMEM,
4,CIR - 07_juillet - 2026 - 000041_FCLI,CIRALB,000041_FCLI,01_Roulements,000041_FFOUR,487042-FAIR,H2307,MANCHON DE SERRAGE,10.37,1.0,...,T3,S2,454310,5502265438,189734,26-212765,,TIMK H2307,000099_FMEM,
5,CIR - 07_juillet - 2026 - 000041_FCLI,CIRALB,000041_FCLI,01_Roulements,000041_FFOUR,502389-FAIR,23218EJW33C3,"RLT A ROT. SUR RLX. 90X160X52,4",167.80,1.0,...,T3,S2,455554,5502266101,190711,26-212766,,TIMK 23218EJW33C3,000099_FMEM,
6,CIR - 07_juillet - 2026 - 000041_FCLI,CIRALB,000041_FCLI,01_Roulements,000041_FFOUR,758615-FAIR,UK207,RLT AUTO-ALIG.ALESA.CONIQ,13.22,1.0,...,T3,S2,454310,5502265438,189734,26-212765,,TIMK UK207,000099_FMEM,
7,CIR - 07_juillet - 2026 - 000041_FCLI,CIRALB,000041_FCLI,02_Transmission mecanique,000436_FFOUR,,POLYFLEX12,COURROIE RONDE D12,12.01,16.0,...,T3,S2,437955,5502258788,192120,26-212760,,MAFD POLYFLEX12,000099_FMEM,
8,CIR - 07_juillet - 2026 - 000041_FCLI,CIRALB,000041_FCLI,03_Transmission electromecanique,000436_FFOUR,,342171,COUVERCLE L100 GC,28.50,3.0,...,T3,S2,332919,5502230992,201307,26-212759,,LEG1 342171,000099_FMEM,
9,CIR - 07_juillet - 2026 - 000041_FCLI,CIRALB,000041_FCLI,03_Transmission electromecanique,000436_FFOUR,,342152,COUVERCLE L200 GC,43.90,6.0,...,T3,S2,332919,5502230992,201307,26-212759,,LEG1 342152,000099_FMEM,

In [309]:
inp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7230 entries, 0 to 7229
Data columns (total 27 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   code_of_integration         7230 non-null   string
 1   member_branch_id            7230 non-null   string
 2   plant_id                    7230 non-null   string
 3   product_family_id           7230 non-null   string
 4   supplier_id                 7230 non-null   object
 5   product_id                  7230 non-null   object
 6   supplier_product_reference  7230 non-null   string
 7   product_description         7230 non-null   string
 8   unit_net_price              7230 non-null   float64
 9   quantity                    7230 non-null   float64
 10  turnover                    7230 non-null   float64
 11  price_per                   7230 non-null   int64
 12  sales_unit                  7230 non-null   object
 13  delivery_date               7230 non-null   object
 14  invoice_date                7230 non-null   object
 15  year                        7230 non-null   int64
 16  month                       7230 non-null   object
 17  quarter                     7230 non-null   object
 18  semester                    7230 non-null   object
 19  member_order_nb             7230 non-null   string
 20  customer_order_nb           7230 non-null   string
 21  deliver_note                7230 non-null   string
 22  invoice_nb                  7230 non-null   string
 23  customer_reference          7230 non-null   string
 24  member_internal_reference   7230 non-null   string
 25  member_id                   7230 non-null   string
 26  buying_member_id            7230 non-null   object
dtypes: float64(3), int64(2), object(9), string(13)
memory usage: 1.5+ MB

## verify data ##

load master data

In [310]:
plants_df = pd.read_pickle('./data/plants.pkl')
plants_df.head()

,CUSTOMER_ID,PLANT_ID,PLANT_NAME,COUNTRY,CITY,SECTOR,CUSTOMER_INTERNAL_ID,PLANT_CLOSED
0,042316_FCLI,042319_FCLI,ABBOTT - Abbott Biologicals - NL - 8121 AA - OLST,NL,OLST,PHARMACEUTICAL,217,None
1,042316_FCLI,042318_FCLI,ABBOTT - Abbott Healthcare Products - NL - 138...,NL,WEESP,PHARMACEUTICAL,217,None
2,042316_FCLI,042317_FCLI,ABBOTT - Abbott Laboratories - DE - 31535 - NE...,DE,NEUSTADT AM RÜBENBERGE,PHARMACEUTICAL,217,None
3,042316_FCLI,042320_FCLI,ABBOTT - Abbott Laboratories - NL - 8041 AK - ...,NL,ZWOLLE,PHARMACEUTICAL,217,None
4,005343_FCLI,030987_FCLI,AMCOR - Amcor Flexibles - BE - 6031 - Monceau-...,BE,MONCEAU-SUR-SAMBRE,PACKAGING (PLASTIC AND CARDBOARD),064,YES

In [311]:
productfamilies_df = pd.read_pickle('./data/productfamilies.pkl')
productfamilies_df.head()

,PRODUCTFAMILY_ID,PRODUCTFAMILY_CODE,PRODUCTFAMILY_NAME
0,01_Roulements,01,"Bearings (bearing, housing)"
1,02_Transmission mecanique,02,Mechanical Transmission
2,03_Transmission electromecanique,03,Electromechanically transmission (motors …)
3,04_Guidage,04,Linear motion
4,05_Etancheite,05,Sealing

In [312]:
members_df = pd.read_pickle('./data/members.pkl')
members_df.head()

     MEMBER_ID MEMBER_NAME COUNTRY
0  000115_FMEM        ABCO      UK
1  000097_FMEM     KUHFUSS      DE
2  000109_FMEM    BIERREDI      IT
3  000096_FMEM   BOIE GMBH      DE
4  000099_FMEM         CIR      FR

In [313]:
branches_df = pd.read_pickle('./data/branches.pkl')
branches_df.head()

     MEMBER_ID BRANCH_ID      BRANCH_NAME MEMBER_NAME BRANCH_CLOSED
0  000099_FMEM    CIRALB         CIR Albi         CIR          None
1  000099_FMEM    CIRBEZ      CIR Beziers         CIR          None
2  000099_FMEM    CIRMER     CIR Bordeaux         CIR          None
3  000099_FMEM    CIRCAR  CIR Carcassonne         CIR          None
4  000099_FMEM    CIRCAS      CIR Castres         CIR          None

In [314]:
suppliers_df = pd.read_pickle('./data/suppliers.pkl')
suppliers_df.head()

    SUPPLIER_ID                SUPPLIER_NAME
0  000436_FFOUR                 DIVERS/OTHER
1  000094_FFOUR                          3 M
2  000095_FFOUR  ABA FRANCE (SERFLEX)= NORMA
3  031147_FFOUR                          ABB
4  000096_FFOUR                          ACC

In [315]:
months_df = pd.read_pickle('./data/months.pkl')
months_df.head()

     MONTH_ID MONTH_CODE   MONTH_NAME
0  01_janvier         01   01_january
1  02_fevrier         02  02_february
2     03_mars         03     03_march
3    04_avril         04     04_april
4      05_mai         05       05_may

create new dataframe

In [316]:
df = pd.DataFrame({
    "code_of_integration": pd.Series(dtype="str"),
    "customer_id": pd.Series(dtype="str"),
    "plant_id": pd.Series(dtype="str"),
    "member_id": pd.Series(dtype="str"),
    "member_branch_id": pd.Series(dtype="str"),
    "product_family_id": pd.Series(dtype="str"),
    "quantity": pd.Series(dtype="float"),
    "turnover": pd.Series(dtype="float"),
    "supplier_product_reference": pd.Series(dtype="str"),
    "product_description": pd.Series(dtype="str"),
    "supplier_id": pd.Series(dtype="str"),
    "invoice_date": pd.Series(dtype="str"),
    "year": pd.Series(dtype="int"),
    "month": pd.Series(dtype="int"),
    "customer_order_nb": pd.Series(dtype="str"),
    "member_order_nb": pd.Series(dtype="str")
})

loop through dataframe and verify data

In [317]:
count_import = 0
count_reject = 0
count_member_to_member = 0
count_purchase = 0

reject_msg = []

for index, row in inp_df.iterrows():
    import_row = True
    reject_reason = []

    buying_member_id = row['buying_member_id'].strip()
    member_id = row['member_id'].strip()
    
    # drop member-to-member turnover
    if buying_member_id != "" and member_id != "":
        count_member_to_member += 1
        continue

    # drop supplier turnover
    plant_id = row['plant_id'].strip()
    product_family_code = row['product_family_id'].strip()
    branch_id = row['member_branch_id'].strip()

    if plant_id == "" and product_family_code == "" and branch_id == "":
        count_purchase += 1
        continue
    
    # check invoice date
    invoice_date = row['invoice_date'].strip()

    if invoice_date == "":
        import_row = False
        reject_reason.append('inovice date must not be empty')
        
    elif not re.fullmatch(r"\d{4}-\d{2}-\d{2}", invoice_date):
        import_row = False
        reject_reason.append('inovice date ' + invoice_date + ' is not valid')

    # check plant id
    customer_id = ""

    if plant_id == "":
        import_row = False
        reject_reason.append('plant id must not be empty')
    else:
        plant_entries = plants_df[plants_df['PLANT_ID'] == plant_id]
        if len(plant_entries) == 0:
            import_row = False
            reject_reason.append('plant id ' + row['plant_id'] + ' is not valid')
        else:
            customer_id = plant_entries.iloc[0]['CUSTOMER_INTERNAL_ID']

    # check product family id
    product_family_code = row['product_family_id'].strip()

    if product_family_code == "":
        import_row = False
        reject_reason.append('product family id must not be empty')
    else:
        family_entries = productfamilies_df[productfamilies_df['PRODUCTFAMILY_ID'] == product_family_code]
        if len(family_entries) > 0:
            product_family_code = family_entries.iloc[0]['PRODUCTFAMILY_CODE']
        else:
            if len(product_family_code) < 2:
                product_family_code = product_family_code.zfill(2)

            if not (productfamilies_df['PRODUCTFAMILY_CODE'] == product_family_code).any():
                import_row = False
                reject_reason.append('product family ' + row['product_family_id'] + ' is not valid')

    # check member id
    if member_id == "":
        import_row = False
        reject_reason.append('member id must not be empty')
    else:
        if not (members_df['MEMBER_ID'] == member_id).any():
            import_row = False
            reject_reason.append('member ' + member_id + ' is not valid')

    # check branch id
    branch_id = row['member_branch_id'].strip()

    if branch_id == "":
        import_row = False
        reject_reason.append('branch id must not be empty')
    elif not (branches_df['BRANCH_ID'] == branch_id).any():
        import_row = False
        reject_reason.append('member branch ' + row['member_branch_id'] + ' is not valid')

    # check supplier id
    supplier_id = row['supplier_id'].strip()

    if supplier_id == "":
        import_row = False
        reject_reason.append('supplier id must not be empty')
    elif not (suppliers_df['SUPPLIER_ID'] == supplier_id).any():
        import_row = False
        reject_reason.append('supplier ' + row['supplier_id'] + ' is not valid')

    # check year
    year = row['year']

    if year == "":
        import_row = False
        reject_reason.append('year must not be empty')
    elif isinstance(year, (int, float)):
        year = int(year)
    else:
        try:
            year = int(year)
        except:
            import_row = False
            reject_reason.append('year ' + row['year'] + ' is not valid')

    # check month
    month = row['month']
    
    if month == "":
        import_row = False
        reject_reason.append('month must not be empty')
    elif isinstance(month, (int, float)):
        month = int(row['month'])
        if month < 1 or month > 12:
            import_row = False
            reject_reason.append('month ' + row['month'] + ' is not valid')
    else:
        month_entries = months_df[months_df['MONTH_ID'] == month]
        if len(month_entries) > 0:
            month = int(month_entries.iloc[0]['MONTH_CODE'])
        else:
            import_row = False
            reject_reason.append('month ' + row['month'] + ' is not valid')

    # check quantity
    quantity = row['quantity']
    if isinstance(quantity, (int, float)):
        quantity = round(quantity,2)
    else:
        try:
            quantity = round(float(quantity),2)
        except:
            import_row = False
            reject_reason.append('quantity ' + row['quantity'] + ' is not valid')

    # check turnover
    turnover = row['turnover']
    if isinstance(turnover, (int, float)):
        turnover = round(turnover,2)
    else:
        try:
            turnover = round(float(turnover),2)
        except:
            import_row = False
            reject_reason.append('turnover ' + row['turnover'] + ' is not valid')

    if import_row:
        new_row = {
            "code_of_integration" : row['code_of_integration'],
            "customer_id": customer_id,
            "plant_id": plant_id,
            "member_id": member_id,
            "member_branch_id": branch_id,
            "product_family_id": product_family_code,
            "quantity": quantity,
            "turnover": turnover,
            "supplier_product_reference": row['supplier_product_reference'],
            "product_description": row['product_description'],
            "supplier_id": supplier_id,
            "invoice_date": invoice_date,
            "year": year,
            "month": month,
            "customer_order_nb": row['customer_order_nb'],
            "member_order_nb": row['member_order_nb']
        }

        df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)

        count_import += 1
    else:
        count_reject += 1
        reject_str = ", ".join(reject_reason)
        reject_msg.append(f"{index} : {reject_str}") 

result_msg = f"imported {count_import} lines, rejected {count_reject} lines, ignored {count_member_to_member} member-to-member lines and {count_purchase} purchase lines"

In [318]:
print(result_msg)

imported 342 lines, rejected 6888 lines, ignored 0 member-to-member lines and 0 purchase lines

In [319]:
print(reject_msg)

['0 : plant id 000041_FCLI is not valid', '1 : plant id 000041_FCLI is not valid', '2 : plant id 000041_FCLI is not valid', '3 : plant id 000041_FCLI is not valid', '4 : plant id 000041_FCLI is not valid', '5 : plant id 000041_FCLI is not valid', '6 : plant id 000041_FCLI is not valid', '7 : plant id 000041_FCLI is not valid', '8 : plant id 000041_FCLI is not valid', '9 : plant id 000041_FCLI is not valid', '10 : plant id 000041_FCLI is not valid', '11 : plant id 000041_FCLI is not valid', '12 : plant id 000041_FCLI is not valid', '13 : plant id 000041_FCLI is not valid', '14 : plant id 000041_FCLI is not valid', '15 : plant id 000041_FCLI is not valid', '16 : plant id 000041_FCLI is not valid', '17 : plant id 000041_FCLI is not valid', '18 : plant id 000041_FCLI is not valid', '19 : plant id 000041_FCLI is not valid', '20 : plant id 000041_FCLI is not valid', '21 : plant id 000041_FCLI is not valid', '22 : plant id 000041_FCLI is not valid', '23 : plant id 000041_FCLI is not valid', '24 : plant id 000051_FCLI is not valid', '25 : plant id 000051_FCLI is not valid', '26 : plant id 000051_FCLI is not valid', '27 : plant id 000055_FCLI is not valid', '28 : plant id 000055_FCLI is not valid', '29 : plant id 000055_FCLI is not valid', '30 : plant id 000055_FCLI is not valid', '31 : plant id 000063_FCLI is not valid', '32 : plant id 000063_FCLI is not valid', '33 : plant id 000067_FCLI is not valid, member branch CIRCOL is not valid', '34 : plant id 000067_FCLI is not valid, member branch CIRCOL is not valid', '35 : plant id 000067_FCLI is not valid, member branch CIRCOL is not valid', '36 : plant id 000093_FCLI is not valid', '37 : plant id 000098_FCLI is not valid', '38 : plant id 000098_FCLI is not valid', '39 : plant id 000112_FCLI is not valid', '40 : plant id 000112_FCLI is not valid', '41 : plant id 000112_FCLI is not valid', '42 : plant id 000112_FCLI is not valid', '43 : plant id 000112_FCLI is not valid', '44 : plant id 000112_FCLI is not valid', '45 : plant id 000112_FCLI is not valid', '46 : plant id 000112_FCLI is not valid', '47 : plant id 000112_FCLI is not valid', '48 : plant id 000112_FCLI is not valid', '49 : plant id 000112_FCLI is not valid', '50 : plant id 000112_FCLI is not valid', '51 : plant id 000112_FCLI is not valid', '52 : plant id 000117_FCLI is not valid', '53 : plant id 000117_FCLI is not valid', '54 : plant id 000117_FCLI is not valid', '55 : plant id 000117_FCLI is not valid', '56 : plant id 000117_FCLI is not valid', '57 : plant id 000117_FCLI is not valid', '58 : plant id 000118_FCLI is not valid', '59 : plant id 000118_FCLI is not valid', '60 : plant id 000148_FCLI is not valid, member branch CIRCOL is not valid', '61 : plant id 000148_FCLI is not valid, member branch CIRCOL is not valid', '62 : plant id 000148_FCLI is not valid, member branch CIRCOL is not valid', '63 : plant id 000148_FCLI is not valid, member branch CIRCOL is not valid', '64 : plant id 000151_FCLI is not valid', '65 : plant id 000151_FCLI is not valid', '66 : plant id 000152_FCLI is not valid, member branch CIRCOL is not valid', '67 : plant id 000163_FCLI is not valid', '68 : plant id 000163_FCLI is not valid', '69 : plant id 000163_FCLI is not valid', '70 : plant id 000163_FCLI is not valid', '71 : plant id 000163_FCLI is not valid', '72 : plant id 000163_FCLI is not valid', '73 : plant id 000163_FCLI is not valid', '74 : plant id 000188_FCLI is not valid', '75 : plant id 000188_FCLI is not valid', '76 : plant id 000188_FCLI is not valid', '77 : plant id 000188_FCLI is not valid', '78 : plant id 000188_FCLI is not valid', '79 : plant id 000188_FCLI is not valid', '80 : plant id 000188_FCLI is not valid', '81 : plant id 000188_FCLI is not valid', '82 : plant id 000188_FCLI is not valid', '83 : plant id 000188_FCLI is not valid', '84 : plant id 000188_FCLI is not valid', '85 : plant id 000188_FCLI is not valid', '86 : plant id 000188_FCLI is not valid', '87 : plant id 000188_FCLI is not valid', '88 : plant id 000188_FCLI is not valid', '89 : plant id 000188_FCLI is not valid', '90 : plant id 000188_FCLI is not valid', '91 : plant id 000188_FCLI is not valid', '92 : plant id 000188_FCLI is not valid', '93 : plant id 000188_FCLI is not valid', '94 : plant id 000188_FCLI is not valid', '95 : plant id 000188_FCLI is not valid', '96 : plant id 000188_FCLI is not valid', '97 : plant id 000188_FCLI is not valid', '98 : plant id 000188_FCLI is not valid', '99 : plant id 000188_FCLI is not valid', '100 : plant id 000188_FCLI is not valid', '101 : plant id 000188_FCLI is not valid', '102 : plant id 000188_FCLI is not valid', '103 : plant id 000188_FCLI is not valid', '104 : plant id 000188_FCLI is not valid', '105 : plant id 000188_FCLI is not valid', '106 : plant id 000188_FCLI is not valid', '107 : plant id 000188_FCLI is not valid', '108 : plant id 000235_FCLI is not valid', '109 : plant id 000235_FCLI is not valid', '110 : plant id 000235_FCLI is not valid', '111 : plant id 000235_FCLI is not valid', '112 : plant id 000235_FCLI is not valid', '113 : plant id 000235_FCLI is not valid', '114 : plant id 000235_FCLI is not valid', '115 : plant id 000303_FCLI is not valid', '116 : plant id 000402_FCLI is not valid', '117 : plant id 000402_FCLI is not valid', '118 : plant id 000483_FCLI is not valid', '119 : plant id 000483_FCLI is not valid', '120 : plant id 000483_FCLI is not valid', '121 : plant id 000483_FCLI is not valid', '122 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '123 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '124 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '125 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '126 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '127 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '128 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '129 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '130 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '131 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '132 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '133 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '134 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '135 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '136 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '137 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '138 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '139 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '140 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '141 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '142 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '143 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '144 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '145 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '146 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '147 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '148 : plant id 000537_FCLI is not valid, member branch CIRCOL is not valid', '149 : plant id 000538_FCLI is not valid', '150 : plant id 000540_FCLI is not valid', '151 : plant id 000540_FCLI is not valid', '152 : plant id 000540_FCLI is not valid', '153 : plant id 000540_FCLI is not valid', '154 : plant id 000540_FCLI is not valid', '155 : plant id 000540_FCLI is not valid', '156 : plant id 000540_FCLI is not valid', '157 : plant id 000540_FCLI is not valid', '158 : plant id 000540_FCLI is not valid', '159 : plant id 000540_FCLI is not valid', '160 : plant id 000540_FCLI is not valid', '161 : plant id 000540_FCLI is not valid', '162 : plant id 000540_FCLI is not valid', '163 : plant id 000540_FCLI is not valid', '164 : plant id 000542_FCLI is not valid', '165 : plant id 000542_FCLI is not valid', '166 : plant id 000542_FCLI is not valid', '167 : plant id 000542_FCLI is not valid', '168 : plant id 000542_FCLI is not valid', '169 : plant id 000542_FCLI is not valid', '170 : plant id 000542_FCLI is not valid', '171 : plant id 000545_FCLI is not valid', '172 : plant id 000545_FCLI is not valid', '173 : plant id 000545_FCLI is not valid', '174 : plant id 000545_FCLI is not valid', '175 : plant id 000545_FCLI is not valid', '176 : plant id 000545_FCLI is not valid', '177 : plant id 000545_FCLI is not valid', '178 : plant id 000545_FCLI is not valid', '179 : plant id 000545_FCLI is not valid', '180 : plant id 000545_FCLI is not valid', '181 : plant id 000545_FCLI is not valid', '182 : plant id 000545_FCLI is not valid', '183 : plant id 000545_FCLI is not valid', '184 : plant id 000545_FCLI is not valid', '185 : plant id 000545_FCLI is not valid', '186 : plant id 000545_FCLI is not valid', '187 : plant id 000545_FCLI is not valid', '188 : plant id 000545_FCLI is not valid', '189 : plant id 000545_FCLI is not valid', '190 : plant id 000545_FCLI is not valid', '191 : plant id 000545_FCLI is not valid', '192 : plant id 000545_FCLI is not valid', '193 : plant id 000545_FCLI is not valid', '194 : plant id 000545_FCLI is not valid', '195 : plant id 000545_FCLI is not valid', '196 : plant id 000545_FCLI is not valid', '197 : plant id 000545_FCLI is not valid', '198 : plant id 000545_FCLI is not valid', '199 : plant id 000545_FCLI is not valid', '200 : plant id 000545_FCLI is not valid', '201 : plant id 000545_FCLI is not valid', '202 : plant id 000545_FCLI is not valid', '203 : plant id 000545_FCLI is not valid', '204 : plant id 000545_FCLI is not valid', '205 : plant id 000545_FCLI is not valid', '206 : plant id 000545_FCLI is not valid', '207 : plant id 000545_FCLI is not valid', '208 : plant id 000545_FCLI is not valid', '209 : plant id 000545_FCLI is not valid', '210 : plant id 000545_FCLI is not valid', '211 : plant id 000545_FCLI is not valid', '212 : plant id 000545_FCLI is not valid', '213 : plant id 000545_FCLI is not valid', '214 : plant id 000545_FCLI is not valid', '215 : plant id 000545_FCLI is not valid', '216 : plant id 000545_FCLI is not valid', '217 : plant id 000546_FCLI is not valid', '218 : plant id 000546_FCLI is not valid', '219 : plant id 000546_FCLI is not valid', '220 : plant id 000546_FCLI is not valid', '221 : plant id 000546_FCLI is not valid', '222 : plant id 000546_FCLI is not valid', '223 : plant id 000546_FCLI is not valid', '224 : plant id 000546_FCLI is not valid', '225 : plant id 000546_FCLI is not valid', '226 : plant id 000546_FCLI is not valid', '227 : plant id 000546_FCLI is not valid', '228 : plant id 000546_FCLI is not valid', '229 : plant id 000546_FCLI is not valid', '230 : plant id 000546_FCLI is not valid', '231 : plant id 000546_FCLI is not valid', '232 : plant id 000546_FCLI is not valid', '233 : plant id 000546_FCLI is not valid', '234 : plant id 000546_FCLI is not valid', '235 : plant id 000546_FCLI is not valid', '236 : plant id 000546_FCLI is not valid', '237 : plant id 000546_FCLI is not valid', '238 : plant id 000546_FCLI is not valid', '239 : plant id 000546_FCLI is not valid', '240 : plant id 000546_FCLI is not valid', '241 : plant id 000546_FCLI is not valid', '242 : plant id 000546_FCLI is not valid', '243 : plant id 000546_FCLI is not valid', '244 : plant id 000546_FCLI is not valid', '245 : plant id 000546_FCLI is not valid', '246 : plant id 000546_FCLI is not valid', '247 : plant id 000546_FCLI is not valid', '248 : plant id 000546_FCLI is not valid', '249 : plant id 000546_FCLI is not valid', '250 : plant id 000546_FCLI is not valid', '251 : plant id 000549_FCLI is not valid', '252 : plant id 000549_FCLI is not valid', '253 : plant id 000549_FCLI is not valid', '254 : plant id 000549_FCLI is not valid', '255 : plant id 000549_FCLI is not valid', '256 : plant id 000549_FCLI is not valid', '257 : plant id 000549_FCLI is not valid', '258 : plant id 000549_FCLI is not valid', '259 : plant id 000549_FCLI is not valid', '260 : plant id 000549_FCLI is not valid', '261 : plant id 000549_FCLI is not valid', '262 : plant id 000549_FCLI is not valid', '263 : plant id 000549_FCLI is not valid', '264 : plant id 000549_FCLI is not valid', '265 : plant id 000549_FCLI is not valid', '266 : plant id 000549_FCLI is not valid', '267 : plant id 000549_FCLI is not valid', '268 : plant id 000549_FCLI is not valid', '269 : plant id 000549_FCLI is not valid', '270 : plant id 000550_FCLI is not valid', '271 : plant id 000550_FCLI is not valid', '272 : plant id 000550_FCLI is not valid', '273 : plant id 000550_FCLI is not valid', '274 : plant id 000550_FCLI is not valid', '275 : plant id 000550_FCLI is not valid', '276 : plant id 000550_FCLI is not valid', '277 : plant id 000550_FCLI is not valid', '278 : plant id 000550_FCLI is not valid', '279 : plant id 000550_FCLI is not valid', '280 : plant id 000550_FCLI is not valid', '281 : plant id 000550_FCLI is not valid', '282 : plant id 000550_FCLI is not valid', '283 : plant id 000550_FCLI is not valid', '284 : plant id 000550_FCLI is not valid', '285 : plant id 000550_FCLI is not valid', '286 : plant id 000550_FCLI is not valid', '287 : plant id 000550_FCLI is not valid', '288 : plant id 000550_FCLI is not valid', '289 : plant id 000550_FCLI is not valid', '290 : plant id 000550_FCLI is not valid', '291 : plant id 000550_FCLI is not valid', '292 : plant id 000550_FCLI is not valid', '293 : plant id 000550_FCLI is not valid', '294 : plant id 000550_FCLI is not valid', '295 : plant id 000550_FCLI is not valid', '296 : plant id 000550_FCLI is not valid', '297 : plant id 000550_FCLI is not valid', '298 : plant id 000550_FCLI is not valid', '299 : plant id 000550_FCLI is not valid', '300 : plant id 000550_FCLI is not valid', '301 : plant id 000550_FCLI is not valid', '302 : plant id 000550_FCLI is not valid', '303 : plant id 000550_FCLI is not valid', '304 : plant id 000550_FCLI is not valid', '305 : plant id 000550_FCLI is not valid', '306 : plant id 000550_FCLI is not valid', '307 : plant id 000550_FCLI is not valid', '308 : plant id 000550_FCLI is not valid', '309 : plant id 000550_FCLI is not valid', '310 : plant id 000550_FCLI is not valid', '311 : plant id 000550_FCLI is not valid', '312 : plant id 000550_FCLI is not valid', '313 : plant id 000550_FCLI is not valid', '314 : plant id 000550_FCLI is not valid', '315 : plant id 000550_FCLI is not valid', '316 : plant id 000550_FCLI is not valid', '317 : plant id 000550_FCLI is not valid', '318 : plant id 000550_FCLI is not valid', '319 : plant id 000550_FCLI is not valid', '320 : plant id 000550_FCLI is not valid', '321 : plant id 000550_FCLI is not valid', '322 : plant id 000550_FCLI is not valid', '323 : plant id 000550_FCLI is not valid', '324 : plant id 000550_FCLI is not valid', '325 : plant id 000550_FCLI is not valid', '326 : plant id 000613_FCLI is not valid', '327 : plant id 000613_FCLI is not valid', '328 : plant id 000613_FCLI is not valid', '329 : plant id 000613_FCLI is not valid', '330 : plant id 000613_FCLI is not valid', '331 : plant id 000613_FCLI is not valid', '332 : plant id 000613_FCLI is not valid', '333 : plant id 000613_FCLI is not valid', '334 : plant id 000613_FCLI is not valid', '335 : plant id 000613_FCLI is not valid', '336 : plant id 000613_FCLI is not valid', '337 : plant id 000613_FCLI is not valid', '338 : plant id 000613_FCLI is not valid', '339 : plant id 000613_FCLI is not valid', '340 : plant id 000613_FCLI is not valid', '341 : plant id 000613_FCLI is not valid', '342 : plant id 000613_FCLI is not valid', '343 : plant id 000613_FCLI is not valid', '344 : plant id 000613_FCLI is not valid', '345 : plant id 000613_FCLI is not valid', '346 : plant id 000613_FCLI is not valid', '347 : plant id 000613_FCLI is not valid', '348 : plant id 000613_FCLI is not valid', '349 : plant id 000613_FCLI is not valid', '350 : plant id 000613_FCLI is not valid', '351 : plant id 000613_FCLI is not valid', '352 : plant id 000613_FCLI is not valid', '353 : plant id 000613_FCLI is not valid', '354 : plant id 000613_FCLI is not valid', '355 : plant id 000614_FCLI is not valid, member branch CIRCOL is not valid', '356 : plant id 000614_FCLI is not valid, member branch CIRCOL is not valid', '357 : plant id 000614_FCLI is not valid, member branch CIRCOL is not valid', '358 : plant id 000614_FCLI is not valid, member branch CIRCOL is not valid', '359 : plant id 000614_FCLI is not valid, member branch CIRCOL is not valid', '360 : plant id 000614_FCLI is not valid, member branch CIRCOL is not valid', '361 : plant id 000614_FCLI is not valid, member branch CIRCOL is not valid', '362 : plant id 000614_FCLI is not valid, member branch CIRCOL is not valid', '363 : plant id 000614_FCLI is not valid, member branch CIRCOL is not valid', '364 : plant id 000614_FCLI is not valid, member branch CIRCOL is not valid', '365 : plant id 000614_FCLI is not valid, member branch CIRCOL is not valid', '366 : plant id 000614_FCLI is not valid, member branch CIRCOL is not valid', '367 : plant id 000614_FCLI is not valid, member branch CIRCOL is not valid', '368 : plant id 000614_FCLI is not valid, member branch CIRCOL is not valid', '369 : plant id 000614_FCLI is not valid, member branch CIRCOL is not valid', '370 : plant id 000614_FCLI is not valid, member branch CIRCOL is not valid', '371 : plant id 000614_FCLI is not valid, member branch CIRCOL is not valid', '372 : plant id 000614_FCLI is not valid, member branch CIRCOL is not valid', '373 : plant id 000614_FCLI is not valid, member branch CIRCOL is not valid', '374 : plant id 000614_FCLI is not valid, member branch CIRCOL is not valid', '375 : plant id 000614_FCLI is not valid, member branch CIRCOL is not valid', '376 : plant id 000614_FCLI is not valid, member branch CIRCOL is not valid', '377 : plant id 000614_FCLI is not valid, member branch CIRCOL is not valid', '378 : plant id 000615_FCLI is not valid, member branch CIRCOL is not valid', '379 : plant id 000615_FCLI is not valid, member branch CIRCOL is not valid', '380 : plant id 000615_FCLI is not valid', '381 : plant id 000627_FCLI is not valid', '382 : plant id 000627_FCLI is not valid', '383 : plant id 000627_FCLI is not valid', '384 : plant id 000627_FCLI is not valid', '385 : plant id 000627_FCLI is not valid', '386 : plant id 000627_FCLI is not valid', '387 : plant id 000627_FCLI is not valid', '388 : plant id 000627_FCLI is not valid', '389 : plant id 000627_FCLI is not valid', '390 : plant id 000627_FCLI is not valid', '391 : plant id 000627_FCLI is not valid', '392 : plant id 000627_FCLI is not valid', '393 : plant id 000627_FCLI is not valid', '394 : plant id 000627_FCLI is not valid', '395 : plant id 000627_FCLI is not valid', '396 : plant id 000627_FCLI is not valid', '397 : plant id 000627_FCLI is not valid', '398 : plant id 000627_FCLI is not valid', '399 : plant id 000627_FCLI is not valid', '400 : plant id 000627_FCLI is not valid', '401 : plant id 000627_FCLI is not valid', '402 : plant id 000627_FCLI is not valid', '403 : plant id 000627_FCLI is not valid', '404 : plant id 000627_FCLI is not valid', '405 : plant id 000627_FCLI is not valid', '406 : plant id 000627_FCLI is not valid', '407 : plant id 000627_FCLI is not valid', '408 : plant id 000627_FCLI is not valid', '409 : plant id 000627_FCLI is not valid', '410 : plant id 000627_FCLI is not valid', '411 : plant id 000627_FCLI is not valid', '412 : plant id 000627_FCLI is not valid', '413 : plant id 000627_FCLI is not valid', '414 : plant id 000627_FCLI is not valid', '415 : plant id 000627_FCLI is not valid', '416 : plant id 000627_FCLI is not valid', '417 : plant id 000627_FCLI is not valid', '418 : plant id 000627_FCLI is not 

In [320]:
df.head()

,code_of_integration,customer_id,plant_id,member_id,member_branch_id,product_family_id,quantity,turnover,supplier_product_reference,product_description,supplier_id,invoice_date,year,month,customer_order_nb,member_order_nb
0,CIR - 07_juillet - 2026 - 000718_FCLI,003,000718_FCLI,000099_FMEM,CIRPAU,01,2.0,41.32,H2311,MANCHON DE SERRAGE,000041_FFOUR,2026-07-31,2026,7,30423053MC,478786
1,CIR - 07_juillet - 2026 - 000718_FCLI,003,000718_FCLI,000099_FMEM,CIRPAU,01,1.0,18.14,H2311,MANCHON DE SERRAGE,000041_FFOUR,2026-07-31,2026,7,30423244MC,482704
2,CIR - 07_juillet - 2026 - 000718_FCLI,003,000718_FCLI,000099_FMEM,CIRPAU,01,1.0,46.75,UCP211,PALIER SEMELLE DIA.55,000041_FFOUR,2026-07-31,2026,7,30423244MC,482704
3,CIR - 07_juillet - 2026 - 000718_FCLI,003,000718_FCLI,000099_FMEM,CIRPAU,01,2.0,86.66,UCP211,PALIER SEMELLE DIA.55,000041_FFOUR,2026-07-31,2026,7,30423053MC,478786
4,CIR - 07_juillet - 2026 - 000718_FCLI,003,000718_FCLI,000099_FMEM,CIRPAU,01,2.0,62.40,UK211,RLT AUTO-ALIG.CONIQ.55X100X40 H2311,000041_FFOUR,2026-07-31,2026,7,30423053MC,478786

In [321]:
with open(log_file, "a") as logfile:
    logfile.write(result_msg + '\r\n')
    logfile.write("\r\n".join(reject_msg) + '\r\n')

# connect to database #

In [271]:
service_account_file = config["google_account_auth"]
credentials = service_account.Credentials.from_service_account_file(
    service_account_file,
    scopes=["https://www.googleapis.com/auth/cloud-platform"]
)

client = bigquery.Client(credentials=credentials, project=credentials.project_id)

In [272]:
dataset_id = config['dataset_id']
table_id = dataset_id + "." + config['turnover_table']

## delete existing lines with contained codes of integration ##

In [273]:
coi_list = df['code_of_integration'].unique()

if len(coi_list) > 0:
    dml_statement = 'DELETE FROM ' + table_id + ' WHERE code_of_integration IN ('

    first = True
    for coi in coi_list:
        if not first:
            dml_statement += ', '
        dml_statement += "'" + coi + "'"
        first = False

    dml_statement += ')'

    query_job = client.query(dml_statement)
    query_job.result()

## upload data ##

In [274]:
chunk_size = 1000
chunks = [df.iloc[i:i+chunk_size] for i in range(0, len(df), chunk_size)]

In [275]:
job_config = bigquery.LoadJobConfig(
    schema=schema.schema_turnover,
    source_format=bigquery.SourceFormat.NEWLINE_DELIMITED_JSON,
)

upload_results = []
upload_errors = []

for chunk_df in chunks:
    json_data = []
    for index, row in chunk_df.iterrows():  
        json_entry = {}
        json_entry['code_of_integration'] = row['code_of_integration']
        json_entry['customer_id'] = row['customer_id']
        json_entry['plant_id'] = row['plant_id']
        json_entry['member_id'] = row['member_id']
        json_entry['member_branch_id'] = row['member_branch_id']
        json_entry['product_family_id'] = row['product_family_id']
        json_entry['quantity'] = row['quantity']
        json_entry['turnover'] = row['turnover']
        json_entry['supplier_product_reference'] = row['supplier_product_reference']
        json_entry['product_description'] = row['product_description']
        json_entry['supplier_id'] = row['supplier_id']
        json_entry['invoice_date'] = row['invoice_date']
        json_entry['year'] = row['year']
        json_entry['month'] = row['month']
        json_entry['customer_order_nb'] = row['customer_order_nb']
        json_entry['member_order_nb'] = row['member_order_nb']
        json_entry['upload_partner'] = partner
        json_entry['upload_date'] = date
        
        json_data.append(json_entry)

    try:
        load_job = client.load_table_from_json(
            json_data,
            table_id,
            job_config=job_config,
        )
        result = load_job.result()

        upload_results.append(f"uploaded {result.output_rows} successfully to {table_id}")
    except GoogleAPICallError as e:
        upload_errors.append(f"error: upload failed: {e}")

In [276]:
client.close()

check results

In [277]:
with open(log_file, "a") as logfile:
    if len(upload_results) > 0:
        logfile.write("\r\n".join(upload_results));
    if len(upload_errors) > 0:
        logfile.write("\r\n".join(upload_errors));

    if len(upload_errors) == 0:
        result_msg += ", upload successful\r\n"
    else:
        result_msg += ", error uploading data\r\n"
    logfile.write("\r\n")
    logfile.write(result_msg)